"""company_data.py — Base données 47 sociétés BRVM"""

COMPANIES = {
    "SGBC": {"name":"Société Générale CI","full_name":"Société Générale de Banques en Côte d'Ivoire","founded":1962,"sector":"Banque","country":"Côte d'Ivoire","website":"https://www.societegenerale.ci","description":"Filiale du groupe Société Générale, première banque privée de Côte d'Ivoire. Réseau de plus de 50 agences et 150 DAB. Services bancaires retail, corporate et investment banking.","products":["Banque de détail","Crédit immobilier","Banque d'entreprises","Gestion de patrimoine","Monétique"],"markets":["Côte d'Ivoire"],"employees_approx":1800,"reports_url":"https://www.societegenerale.ci/fr/investisseurs","brvm_page":"https://www.brvm.org/fr/valeurs/0/SGBC"},
    "SIBC": {"name":"SIB CI","full_name":"Société Ivoirienne de Banque SA","founded":1962,"sector":"Banque","country":"Côte d'Ivoire","website":"https://www.sib.ci","description":"Banque universelle filiale du groupe Attijariwafa Bank (Maroc). Spécialisée dans le financement des PME/PMI et des particuliers en Côte d'Ivoire.","products":["Crédit PME","Banque de détail","Financement commerce","Mobile banking"],"markets":["Côte d'Ivoire"],"employees_approx":900,"reports_url":"https://www.sib.ci","brvm_page":"https://www.brvm.org/fr/valeurs/0/SIBC"},
    "SNTS": {"name":"Sonatel","full_name":"Société Nationale des Télécommunications du Sénégal","founded":1985,"sector":"Télécommunications","country":"Sénégal","website":"https://www.sonatel.com","description":"Leader des télécommunications en Afrique de l'Ouest, filiale d'Orange SA. Opère sous la marque Orange au Sénégal, Mali, Guinée et Sierra Leone. Plus de 30 millions de clients.","products":["Téléphonie mobile","Internet fixe et mobile","Orange Money","Services entreprises","Fibre optique"],"markets":["Sénégal","Mali","Guinée","Guinée-Bissau","Sierra Leone"],"employees_approx":3500,"reports_url":"https://www.sonatel.com/investisseurs","brvm_page":"https://www.brvm.org/fr/valeurs/0/SNTS"},
    "NSBC": {"name":"NSIA Banque CI","full_name":"NSIA Banque Côte d'Ivoire SA","founded":1997,"sector":"Banque","country":"Côte d'Ivoire","website":"https://www.nsiabanque.ci","description":"Banque universelle du groupe panafricain NSIA. Acteur majeur du financement des grandes entreprises et des projets d'infrastructure en Côte d'Ivoire.","products":["Banque corporative","Financement de projets","Banque de détail","Assurance bancaire"],"markets":["Côte d'Ivoire"],"employees_approx":600,"reports_url":"https://www.nsiabanque.ci","brvm_page":"https://www.brvm.org/fr/valeurs/0/NSBC"},
    "CBIBF": {"name":"Coris Bank International","full_name":"Coris Bank International Burkina Faso SA","founded":2008,"sector":"Banque","country":"Burkina Faso","website":"https://www.corisbankinter.com","description":"Première banque privée burkinabè à capitaux nationaux. Groupe panafricain présent dans 8 pays d'Afrique de l'Ouest. Pionnier de la bancarisation des populations non desservies.","products":["Banque de détail","Microfinance","Banque d'entreprises","Coris Money"],"markets":["Burkina Faso","Mali","Sénégal","Togo","Niger","Côte d'Ivoire","Bénin","Guinée-Bissau"],"employees_approx":2000,"reports_url":"https://www.corisbankinter.com","brvm_page":"https://www.brvm.org/fr/valeurs/0/CBIBF"},
    "BOAB": {"name":"BOA Bénin","full_name":"Bank of Africa Bénin SA","founded":1982,"sector":"Banque","country":"Bénin","website":"https://www.boacgroup.com","description":"Filiale du groupe Bank of Africa (BMCE Group), l'une des premières banques du Bénin avec réseau solide et services digitaux en forte croissance.","products":["Banque de détail","Crédit agricole","Banque d'entreprises","BOA Mobile"],"markets":["Bénin"],"employees_approx":500,"reports_url":"https://www.boacgroup.com","brvm_page":"https://www.brvm.org/fr/valeurs/0/BOAB"},
    "BOABF": {"name":"BOA Burkina Faso","full_name":"Bank of Africa Burkina Faso SA","founded":1998,"sector":"Banque","country":"Burkina Faso","website":"https://www.boacgroup.com","description":"Filiale burkinabè du groupe Bank of Africa. Banque universelle avec fort accent sur la digitalisation au Burkina Faso.","products":["Banque de détail","Financement PME","Banque corporative","BOA Mobile"],"markets":["Burkina Faso"],"employees_approx":450,"reports_url":"https://www.boacgroup.com","brvm_page":"https://www.brvm.org/fr/valeurs/0/BOABF"},
    "BOAC": {"name":"BOA Côte d'Ivoire","full_name":"Bank of Africa Côte d'Ivoire SA","founded":1996,"sector":"Banque","country":"Côte d'Ivoire","website":"https://www.boacgroup.com","description":"Filiale ivoirienne du groupe Bank of Africa. Banque universelle retail et corporate dans les principales villes ivoiriennes.","products":["Banque de détail","Crédit immobilier","Banque d'entreprises","Services digitaux"],"markets":["Côte d'Ivoire"],"employees_approx":400,"reports_url":"https://www.boacgroup.com","brvm_page":"https://www.brvm.org/fr/valeurs/0/BOAC"},
    "BOAM": {"name":"BOA Mali","full_name":"Bank of Africa Mali SA","founded":1982,"sector":"Banque","country":"Mali","website":"https://www.boacgroup.com","description":"L'une des premières banques privées du Mali, filiale Bank of Africa. Rôle clé dans le financement de l'économie malienne.","products":["Banque de détail","Financement commerce","Banque corporative"],"markets":["Mali"],"employees_approx":350,"reports_url":"https://www.boacgroup.com","brvm_page":"https://www.brvm.org/fr/valeurs/0/BOAM"},
    "BOAN": {"name":"BOA Niger","full_name":"Bank of Africa Niger SA","founded":1994,"sector":"Banque","country":"Niger","website":"https://www.boacgroup.com","description":"Filiale nigérienne du groupe Bank of Africa. Banque universelle active dans le financement des entreprises et des ménages au Niger.","products":["Banque de détail","Crédit agricole","Banque d'entreprises"],"markets":["Niger"],"employees_approx":300,"reports_url":"https://www.boacgroup.com","brvm_page":"https://www.brvm.org/fr/valeurs/0/BOAN"},
    "BOAS": {"name":"BOA Sénégal","full_name":"Bank of Africa Sénégal SA","founded":2002,"sector":"Banque","country":"Sénégal","website":"https://www.boacgroup.com","description":"Filiale sénégalaise du groupe Bank of Africa en forte croissance, profitant du dynamisme de l'économie sénégalaise boostée par les découvertes pétrolières.","products":["Banque de détail","Financement PME","Banque corporative","Mobile banking"],"markets":["Sénégal"],"employees_approx":380,"reports_url":"https://www.boacgroup.com","brvm_page":"https://www.brvm.org/fr/valeurs/0/BOAS"},
    "ECOC": {"name":"Ecobank CI","full_name":"Ecobank Côte d'Ivoire SA","founded":1989,"sector":"Banque","country":"Côte d'Ivoire","website":"https://www.ecobank.com/ci","description":"Filiale ivoirienne d'Ecobank Transnational, leader panafricain en 35 pays. Forte plateforme digitale Ecobank App et Ecobank Pay.","products":["Banque de détail","Ecobank Mobile","Banque corporative","Trade finance","Cash management"],"markets":["Côte d'Ivoire"],"employees_approx":800,"reports_url":"https://www.ecobank.com/ci","brvm_page":"https://www.brvm.org/fr/valeurs/0/ECOC"},
    "BICC": {"name":"BICI CI","full_name":"Banque Internationale pour le Commerce et l'Industrie de la Côte d'Ivoire","founded":1966,"sector":"Banque","country":"Côte d'Ivoire","website":"https://www.bici.ci","description":"Banque historique de Côte d'Ivoire, filiale BNP Paribas. Spécialisée dans le financement des grandes entreprises et du commerce international.","products":["Trade finance","Banque corporative","Financement de projets","Cash management"],"markets":["Côte d'Ivoire"],"employees_approx":700,"reports_url":"https://www.bici.ci","brvm_page":"https://www.brvm.org/fr/valeurs/0/BICC"},
    "ORAC": {"name":"Orange CI","full_name":"Orange Côte d'Ivoire SA","founded":1996,"sector":"Télécommunications","country":"Côte d'Ivoire","website":"https://www.orange.ci","description":"Leader télécom en Côte d'Ivoire, filiale d'Orange SA. Plus de 15 millions de clients. Pionnier d'Orange Money qui domine le mobile money ivoirien.","products":["Téléphonie mobile 4G","Orange Money","Internet fixe et mobile","Services B2B","Orange TV"],"markets":["Côte d'Ivoire"],"employees_approx":2500,"reports_url":"https://www.orange.ci","brvm_page":"https://www.brvm.org/fr/valeurs/0/ORAC"},
    "ONTBF": {"name":"Onatel BF","full_name":"Office National des Télécommunications du Burkina Faso","founded":1987,"sector":"Télécommunications","country":"Burkina Faso","website":"https://www.onatel.bf","description":"Opérateur historique télécom du Burkina Faso, contrôlé par l'État et Maroc Telecom. Exploite réseaux fixe et mobile Telmob.","products":["Téléphonie fixe","Réseau mobile Telmob","Internet ADSL/fibre","Services entreprises"],"markets":["Burkina Faso"],"employees_approx":1200,"reports_url":"https://www.onatel.bf","brvm_page":"https://www.brvm.org/fr/valeurs/0/ONTBF"},
    "NTLC": {"name":"Nestlé CI","full_name":"Nestlé Côte d'Ivoire SA","founded":1959,"sector":"Consommation","country":"Côte d'Ivoire","website":"https://www.nestle.ci","description":"Filiale ivoirienne du géant suisse Nestlé. Fabrique et distribue produits alimentaires et boissons avec forte pénétration du marché ivoirien et régional.","products":["Nescafé","Lait Nido","Milo","Maggi","Céréales"],"markets":["Côte d'Ivoire","Afrique de l'Ouest"],"employees_approx":800,"reports_url":"https://www.nestle.ci","brvm_page":"https://www.brvm.org/fr/valeurs/0/NTLC"},
    "STBC": {"name":"SITAB CI","full_name":"Société Ivoirienne des Tabacs","founded":1960,"sector":"Consommation","country":"Côte d'Ivoire","website":"","description":"Fabricant et distributeur de produits du tabac en Côte d'Ivoire, filiale British American Tobacco. Monopole de production de cigarettes sur le marché ivoirien.","products":["Cigarettes","Tabac à rouler","Distribution tabac"],"markets":["Côte d'Ivoire","Afrique de l'Ouest"],"employees_approx":300,"reports_url":"https://www.brvm.org/fr/valeurs/0/STBC","brvm_page":"https://www.brvm.org/fr/valeurs/0/STBC"},
    "UNLC": {"name":"Unilever CI","full_name":"Unilever Côte d'Ivoire SA","founded":1960,"sector":"Consommation","country":"Côte d'Ivoire","website":"","description":"Filiale ivoirienne du groupe Unilever. Produit et distribue biens de consommation courante hygiène, beauté et alimentation.","products":["Omo","Lifebuoy","Knorr","Dove","Close Up","Vaseline"],"markets":["Côte d'Ivoire","Afrique de l'Ouest"],"employees_approx":500,"reports_url":"https://www.brvm.org/fr/valeurs/0/UNLC","brvm_page":"https://www.brvm.org/fr/valeurs/0/UNLC"},
    "SMBC": {"name":"SMB CI","full_name":"Société de Matériaux de Construction","founded":1975,"sector":"Industriel","country":"Côte d'Ivoire","website":"","description":"Producteur de matériaux de construction en Côte d'Ivoire profitant du boom des infrastructures ivoiriennes.","products":["Matériaux de construction","Ciment","Agrégats"],"markets":["Côte d'Ivoire"],"employees_approx":200,"reports_url":"https://www.brvm.org/fr/valeurs/0/SMBC","brvm_page":"https://www.brvm.org/fr/valeurs/0/SMBC"},
    "TTLC": {"name":"TotalEnergies CI","full_name":"TotalEnergies Marketing Côte d'Ivoire SA","founded":1954,"sector":"Énergie","country":"Côte d'Ivoire","website":"https://totalenergies.ci","description":"Filiale ivoirienne de TotalEnergies. Leader distribution carburants en Côte d'Ivoire avec réseau de stations-service et activités lubrifiants et gaz.","products":["Carburants","Lubrifiants Total","Gaz LPG","Bitume"],"markets":["Côte d'Ivoire"],"employees_approx":400,"reports_url":"https://totalenergies.ci","brvm_page":"https://www.brvm.org/fr/valeurs/0/TTLC"},
    "TTLS": {"name":"TotalEnergies Sénégal","full_name":"TotalEnergies Marketing Sénégal SA","founded":1952,"sector":"Énergie","country":"Sénégal","website":"https://totalenergies.sn","description":"Filiale sénégalaise de TotalEnergies. Distribution carburants et gaz, profitant du boom pétrolier avec les découvertes offshore sénégalaises.","products":["Carburants","Lubrifiants","Gaz LPG","Bitume"],"markets":["Sénégal"],"employees_approx":300,"reports_url":"https://totalenergies.sn","brvm_page":"https://www.brvm.org/fr/valeurs/0/TTLS"},
    "CIEC": {"name":"CIE CI","full_name":"Compagnie Ivoirienne d'Électricité","founded":1990,"sector":"Utilités","country":"Côte d'Ivoire","website":"https://www.cie.ci","description":"Concessionnaire distribution électricité en Côte d'Ivoire, filiale ERANOVE. Gère le réseau sur tout le territoire avec plus de 2 millions de clients.","products":["Distribution électricité","Réseau HTA/BT","Raccordement"],"markets":["Côte d'Ivoire"],"employees_approx":3500,"reports_url":"https://www.cie.ci","brvm_page":"https://www.brvm.org/fr/valeurs/0/CIEC"},
    "SDCC": {"name":"SODECI CI","full_name":"Société de Distribution d'Eau de Côte d'Ivoire","founded":1960,"sector":"Utilités","country":"Côte d'Ivoire","website":"https://www.sodeci.ci","description":"Concessionnaire distribution eau potable en Côte d'Ivoire, filiale ERANOVE. Plus d'un million de clients en zones urbaines.","products":["Distribution eau potable","Traitement eau","Réseau hydraulique"],"markets":["Côte d'Ivoire"],"employees_approx":2800,"reports_url":"https://www.sodeci.ci","brvm_page":"https://www.brvm.org/fr/valeurs/0/SDCC"},
    "PALC": {"name":"Palm CI","full_name":"Société Ivoirienne de Palmeraies et de Huileries","founded":1968,"sector":"Agriculture","country":"Côte d'Ivoire","website":"https://www.palmci.ci","description":"Premier producteur huile de palme de Côte d'Ivoire, filiale SIFCA. Exploite plantations industrielles et soutient les planteurs villageois.","products":["Huile de palme brute","Huile de palmiste","Tourteaux"],"markets":["Côte d'Ivoire","Export mondial"],"employees_approx":5000,"reports_url":"https://www.palmci.ci","brvm_page":"https://www.brvm.org/fr/valeurs/0/PALC"},
    "SPHC": {"name":"SAPH CI","full_name":"Société Africaine de Plantations d'Hévéas","founded":1956,"sector":"Agriculture","country":"Côte d'Ivoire","website":"https://www.saph.ci","description":"Leader caoutchouc naturel en Côte d'Ivoire et premier producteur africain, filiale SOCFIN. Vaste réseau de planteurs villageois.","products":["Caoutchouc naturel RSS","TSR","Latex concentré"],"markets":["Côte d'Ivoire","Export Asie/Europe"],"employees_approx":4000,"reports_url":"https://www.saph.ci","brvm_page":"https://www.brvm.org/fr/valeurs/0/SPHC"},
    "SOGC": {"name":"SOGB CI","full_name":"Société des Caoutchoucs de Grand-Béréby","founded":1978,"sector":"Agriculture","country":"Côte d'Ivoire","website":"","description":"Producteur caoutchouc naturel dans l'Ouest de Côte d'Ivoire avec plantation d'hévéas et usine de transformation à Grand-Béréby.","products":["Caoutchouc naturel","Latex"],"markets":["Côte d'Ivoire","Export"],"employees_approx":1500,"reports_url":"https://www.brvm.org/fr/valeurs/0/SOGC","brvm_page":"https://www.brvm.org/fr/valeurs/0/SOGC"},
    "SIVC": {"name":"Erium CI","full_name":"Erium CI (Air Liquide Côte d'Ivoire)","founded":1960,"sector":"Industriel","country":"Côte d'Ivoire","website":"","description":"Producteur et distributeur de gaz industriels en Côte d'Ivoire, filiale Air Liquide. Fournit oxygène, azote et gaz spéciaux aux industries ivoiriennes.","products":["Oxygène industriel","Azote","Gaz rares","Acétylène","Gaz médicaux"],"markets":["Côte d'Ivoire"],"employees_approx":150,"reports_url":"https://www.brvm.org/fr/valeurs/0/SIVC","brvm_page":"https://www.brvm.org/fr/valeurs/0/SIVC"},
    "BICB": {"name":"BICB Bénin","full_name":"Banque Internationale du Commerce et de l'Industrie du Bénin","founded":1989,"sector":"Banque","country":"Bénin","website":"","description":"Banque universelle béninoise active dans le financement du commerce et de l'industrie au Bénin.","products":["Banque de détail","Financement commerce","Banque d'entreprises"],"markets":["Bénin"],"employees_approx":200,"reports_url":"https://www.brvm.org/fr/valeurs/0/BICB","brvm_page":"https://www.brvm.org/fr/valeurs/0/BICB"},
    "LNBB": {"name":"Loterie Nationale Bénin","full_name":"Loterie Nationale du Bénin SA","founded":1974,"sector":"Consommation","country":"Bénin","website":"https://www.lonab.bj","description":"Opérateur national jeux de hasard au Bénin avec monopole légal sur la loterie. Redistribue une partie des revenus à des causes sociales.","products":["Loterie nationale","Jeux de grattage","Jeux en ligne"],"markets":["Bénin"],"employees_approx":250,"reports_url":"https://www.lonab.bj","brvm_page":"https://www.brvm.org/fr/valeurs/0/LNBB"},
    "FTSC": {"name":"Filtisac CI","full_name":"Filtisac Côte d'Ivoire SA","founded":1969,"sector":"Industriel","country":"Côte d'Ivoire","website":"https://www.filtisac.com","description":"Leader africain emballage jute et polypropylène, filiale SIFCA. Fabrique sacs pour cacao, café, coton et autres matières premières agricoles.","products":["Sacs de jute","Sacs polypropylène","Big bags","Emballages industriels"],"markets":["Côte d'Ivoire","Afrique de l'Ouest"],"employees_approx":600,"reports_url":"https://www.filtisac.com","brvm_page":"https://www.brvm.org/fr/valeurs/0/FTSC"},
    "SHEC": {"name":"Vivo Energy CI","full_name":"Vivo Energy Côte d'Ivoire SA","founded":2011,"sector":"Énergie","country":"Côte d'Ivoire","website":"https://www.vivoenergy.com/ci","description":"Distributeur carburants Shell en Côte d'Ivoire, filiale Vivo Energy (Vitol Group). Réseau stations-service Shell avec lubrifiants et gaz LPG.","products":["Carburants Shell","Lubrifiants Helix","Gaz LPG","Boutiques Shell"],"markets":["Côte d'Ivoire"],"employees_approx":200,"reports_url":"https://www.vivoenergy.com/ci","brvm_page":"https://www.brvm.org/fr/valeurs/0/SHEC"},
    "CFAC": {"name":"CFAO Motors CI","full_name":"CFAO Motors Côte d'Ivoire SA","founded":1950,"sector":"Industriel","country":"Côte d'Ivoire","website":"https://www.cfao.com","description":"Distributeur automobile leader en Côte d'Ivoire, filiale CFAO. Distribue Toyota, Honda, Yamaha avec services après-vente.","products":["Distribution automobile","Toyota","Honda","Yamaha motos","Pièces de rechange"],"markets":["Côte d'Ivoire"],"employees_approx":400,"reports_url":"https://www.cfao.com","brvm_page":"https://www.brvm.org/fr/valeurs/0/CFAC"},
    "ETIT": {"name":"Ecobank Togo","full_name":"Ecobank Transnational Incorporated","founded":1985,"sector":"Banque","country":"Togo","website":"https://www.ecobank.com","description":"Holding de la première banque panafricaine présente dans 35 pays avec plus de 700 agences. Pionnier banque digitale en Afrique.","products":["Banque retail","Banque corporative","Investment banking","Ecobank Mobile"],"markets":["35 pays africains"],"employees_approx":15000,"reports_url":"https://www.ecobank.com/investor-relations","brvm_page":"https://www.brvm.org/fr/valeurs/0/ETIT"},
    "SDSC": {"name":"Africa Global Logistics CI","full_name":"Africa Global Logistics Côte d'Ivoire SA","founded":1978,"sector":"Industriel","country":"Côte d'Ivoire","website":"https://www.africagloballogistics.com","description":"Leader logistique portuaire Afrique de l'Ouest, filiale MSC Group. Manutention portuaire, transit douanier et logistique à Abidjan.","products":["Manutention portuaire","Transit douanier","Logistique supply chain","Entreposage"],"markets":["Côte d'Ivoire","Afrique de l'Ouest"],"employees_approx":2000,"reports_url":"https://www.africagloballogistics.com","brvm_page":"https://www.brvm.org/fr/valeurs/0/SDSC"},
    "SLBC": {"name":"SOLIBRA CI","full_name":"Société de Limonaderies et Brasseries d'Afrique","founded":1955,"sector":"Consommation","country":"Côte d'Ivoire","website":"","description":"Brasseur leader en Côte d'Ivoire, filiale Castel Group. Produit bières, sodas et eaux minérales via un dense réseau de distribution.","products":["Bières Flag","Beaufort","Coca-Cola CI","Eaux Awa"],"markets":["Côte d'Ivoire"],"employees_approx":800,"reports_url":"https://www.brvm.org/fr/valeurs/0/SLBC","brvm_page":"https://www.brvm.org/fr/valeurs/0/SLBC"},
    "SCRC": {"name":"Sucrivoire CI","full_name":"Sucrivoire Côte d'Ivoire SA","founded":1971,"sector":"Agriculture","country":"Côte d'Ivoire","website":"","description":"Producteur de sucre en Côte d'Ivoire, filiale SIFCA. Exploite plantations de canne à sucre et raffineries sur le territoire ivoirien.","products":["Sucre blanc","Mélasse","Bagasse","Énergie biomasse"],"markets":["Côte d'Ivoire"],"employees_approx":3000,"reports_url":"https://www.brvm.org/fr/valeurs/0/SCRC","brvm_page":"https://www.brvm.org/fr/valeurs/0/SCRC"},
    "CABC": {"name":"Sicable CI","full_name":"Sicable Côte d'Ivoire SA","founded":1973,"sector":"Industriel","country":"Côte d'Ivoire","website":"","description":"Fabricant de câbles électriques et de télécommunication en Côte d'Ivoire. Fournit les réseaux électriques et télécom ivoiriens.","products":["Câbles électriques","Câbles télécom","Fils et câbles"],"markets":["Côte d'Ivoire"],"employees_approx":300,"reports_url":"https://www.brvm.org/fr/valeurs/0/CABC","brvm_page":"https://www.brvm.org/fr/valeurs/0/CABC"},
    "BNBC": {"name":"Bernabé CI","full_name":"Bernabé Côte d'Ivoire SA","founded":1960,"sector":"Industriel","country":"Côte d'Ivoire","website":"","description":"Distributeur matériaux électriques, sanitaires et de construction en Côte d'Ivoire. Acteur clé approvisionnement secteur BTP ivoirien.","products":["Matériaux électriques","Robinetterie","Quincaillerie","Équipements sanitaires"],"markets":["Côte d'Ivoire"],"employees_approx":250,"reports_url":"https://www.brvm.org/fr/valeurs/0/BNBC","brvm_page":"https://www.brvm.org/fr/valeurs/0/BNBC"},
    "SICC": {"name":"Sicor CI","full_name":"Sicor Côte d'Ivoire SA","founded":1975,"sector":"Industriel","country":"Côte d'Ivoire","website":"","description":"Société industrielle ivoirienne spécialisée dans la transformation de produits agricoles et la fabrication industrielle.","products":["Transformation agricole","Production industrielle"],"markets":["Côte d'Ivoire"],"employees_approx":200,"reports_url":"https://www.brvm.org/fr/valeurs/0/SICC","brvm_page":"https://www.brvm.org/fr/valeurs/0/SICC"},
    "PRSC": {"name":"Tractafric Motors CI","full_name":"Tractafric Motors Côte d'Ivoire SA","founded":1970,"sector":"Industriel","country":"Côte d'Ivoire","website":"","description":"Distributeur engins de chantier et véhicules industriels en Côte d'Ivoire. Représentant Caterpillar et Ford sur le marché ivoirien.","products":["Engins Caterpillar","Ford","Pièces de rechange","SAV"],"markets":["Côte d'Ivoire"],"employees_approx":300,"reports_url":"https://www.brvm.org/fr/valeurs/0/PRSC","brvm_page":"https://www.brvm.org/fr/valeurs/0/PRSC"},
    "ABJC": {"name":"Servair Abidjan CI","full_name":"Servair Abidjan Côte d'Ivoire SA","founded":1975,"sector":"Industriel","country":"Côte d'Ivoire","website":"","description":"Prestataire restauration aérienne et services au sol à l'aéroport international d'Abidjan, filiale Air France Services.","products":["Catering aérien","Services au sol","Restauration collective"],"markets":["Côte d'Ivoire"],"employees_approx":400,"reports_url":"https://www.brvm.org/fr/valeurs/0/ABJC","brvm_page":"https://www.brvm.org/fr/valeurs/0/ABJC"},
    "STAC": {"name":"Setao CI","full_name":"Setao Côte d'Ivoire SA","founded":1958,"sector":"Industriel","country":"Côte d'Ivoire","website":"","description":"Société de travaux publics et de construction en Côte d'Ivoire. Active dans la réalisation d'infrastructures routières et de bâtiments.","products":["Travaux publics","Construction","BTP","Infrastructures routières"],"markets":["Côte d'Ivoire"],"employees_approx":300,"reports_url":"https://www.brvm.org/fr/valeurs/0/STAC","brvm_page":"https://www.brvm.org/fr/valeurs/0/STAC"},
    "UNXC": {"name":"Uniwax CI","full_name":"Uniwax Côte d'Ivoire SA","founded":1970,"sector":"Consommation","country":"Côte d'Ivoire","website":"","description":"Fabricant tissus wax imprimés en Côte d'Ivoire, filiale Vlisco. Produit les célèbres tissus Woodin très prisés en Afrique de l'Ouest.","products":["Tissus wax Woodin","Textiles imprimés","Pagnes africains"],"markets":["Côte d'Ivoire","Afrique de l'Ouest"],"employees_approx":500,"reports_url":"https://www.brvm.org/fr/valeurs/0/UNXC","brvm_page":"https://www.brvm.org/fr/valeurs/0/UNXC"},
    "NEIC": {"name":"NEI-CEDA CI","full_name":"NEI-CEDA Côte d'Ivoire SA","founded":1976,"sector":"Consommation","country":"Côte d'Ivoire","website":"","description":"Société édition, imprimerie et librairie en Côte d'Ivoire. Produit manuels scolaires et matériel pédagogique pour l'Afrique de l'Ouest.","products":["Manuels scolaires","Édition","Imprimerie","Librairie"],"markets":["Côte d'Ivoire","Afrique de l'Ouest"],"employees_approx":200,"reports_url":"https://www.brvm.org/fr/valeurs/0/NEIC","brvm_page":"https://www.brvm.org/fr/valeurs/0/NEIC"},
    "ORGT": {"name":"Oragroup Togo","full_name":"Oragroup SA","founded":2000,"sector":"Banque","country":"Togo","website":"https://www.oragroup.net","description":"Holding bancaire panafricain présent dans 12 pays via ses filiales Orabank. Accompagne PME et particuliers dans leur développement en Afrique.","products":["Banque de détail","Banque d'entreprises","Microfinance","Orabank Mobile"],"markets":["12 pays Afrique de l'Ouest et Centrale"],"employees_approx":2500,"reports_url":"https://www.oragroup.net","brvm_page":"https://www.brvm.org/fr/valeurs/0/ORGT"},
    "SAFC": {"name":"SAFCA CI","full_name":"Société Africaine de Crédit Automobile","founded":1963,"sector":"Banque","country":"Côte d'Ivoire","website":"","description":"Société de financement spécialisée dans le crédit automobile et l'équipement en Côte d'Ivoire.","products":["Crédit automobile","Financement équipement","Leasing"],"markets":["Côte d'Ivoire"],"employees_approx":100,"reports_url":"https://www.brvm.org/fr/valeurs/0/SAFC","brvm_page":"https://www.brvm.org/fr/valeurs/0/SAFC"},
    "SEMC": {"name":"Crown Siem CI","full_name":"Crown Siem Côte d'Ivoire SA","founded":1970,"sector":"Énergie","country":"Côte d'Ivoire","website":"","description":"Société spécialisée dans la production et la distribution d'énergie en Côte d'Ivoire.","products":["Production énergie","Distribution","Maintenance équipements"],"markets":["Côte d'Ivoire"],"employees_approx":150,"reports_url":"https://www.brvm.org/fr/valeurs/0/SEMC","brvm_page":"https://www.brvm.org/fr/valeurs/0/SEMC"},
}

def get_company(ticker):
    t = ticker.upper()
    if t in COMPANIES:
        return {"ticker": t, **COMPANIES[t]}
    return {"ticker": t, "name": t, "sector": "—", "country": "—",
            "description": "Société cotée sur la BRVM.", "products": [], "markets": [],
            "founded": None, "website": "", "employees_approx": None,
            "reports_url": f"https://www.brvm.org/fr/valeurs/0/{t}",
            "brvm_page": f"https://www.brvm.org/fr/valeurs/0/{t}"}

def get_all_tickers():
    return list(COMPANIES.keys())

if __name__ == "__main__":
    c = get_company("SGBC")
    print(f"{c['name']} — {c['sector']} — {c['country']}")
    print(f"Produits: {', '.join(c['products'])}")
    print(f"Total: {len(COMPANIES)} sociétés documentées")
